jobs:
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - bash: |
      curl -LO https://github.com/bazelbuild/bazel/releases/download/0.20.0/bazel-0.20.0-windows-x86_64.exe
      mv bazel-*.exe bazel.exe
      mkdir /c/bazel
      mv bazel.exe /c/bazel
    displayName: 'Install Bazel'
  - bash: |
      # We cannot build Haskell projects yet, so we ensure that we can at least
      # evaluate the WORKSPACE
      /c/bazel/bazel.exe fetch "///tests:ghc" # first '/' gets eaten up

      # We make sure that the Go sdk can be loaded
      /c/bazel/bazel.exe build "///:buildifier" # first '/' gets eaten up
    displayName: 'Run Bazel'
