jobs:
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - bash: |
      curl -LO https://github.com/bazelbuild/bazel/releases/download/0.20.0/bazel-0.20.0-windows-x86_64.exe
      mv bazel-*.exe bazel.exe
      mkdir /c/bazel
      mv bazel.exe /c/bazel
      gcc --version || echo NO GCC
      pacman -S gcc
      gcc --version
      echo $(which gcc)
    displayName: 'Install Bazel'
  - bash: |
      # Simple haskell binary
      /c/bazel/bazel.exe build --compiler=mingw-gcc -s --verbose_failures "///tests/binary-simple"
    displayName: 'Run Bazel'
