version: 2

# NOTE:
#   Disk cache:
#       We don't want to keep old artifacts around so we always build from
#       scratch on master builds and upload the new cache afterwards. Because
#       Circle doesn't allow skipping a "restore_cache" we create a dummy
#       "empty" cache that's only ever pulled on master. Alternatively we could
#       ask Bazel to clean up old items (LRU style) but the documentation is
#       very terse and I could not figure how to do it:
#           https://docs.bazel.build/versions/master/remote-caching.html
#       It also appears that there's ongoing work but the feature is not ready:
#           https://github.com/bazelbuild/bazel/issues/5139
#
#       Currently the disk cache is only implemented for the Darwin builds,
#       which were the slowest ones. There is no reason why a disk cache
#       couldn't be used for the other jobs: I just haven't gotten around to
#       doing it.

jobs:
  build-linux-ghc-bindist:
    docker:
      - image: debian
    working_directory: ~/rules_haskell
    resource_class: large
    steps:
      - checkout
      - run:
          name: Setup test environment
          command: |
            apt-get update
            apt-get install -y wget gnupg golang make libgmp3-dev libtinfo-dev libtinfo5 pkg-config zip g++ zlib1g-dev unzip python python3 bash-completion locales
            echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
            locale-gen
            wget "https://github.com/bazelbuild/bazel/releases/download/0.28.0/bazel_0.28.0-linux-x86_64.deb"
            dpkg -i bazel_0.28.0-linux-x86_64.deb
            echo "common:ci --build_tag_filters -requires_hackage,-requires_lz4,-requires_zlib,-requires_doctest,-requires_c2hs,-requires_threaded_rts,-dont_test_with_bindist" > .bazelrc.local
            # XXX: See .bazelrc [backward compatible options] for the the rational behind this flag
            echo "build --incompatible_use_python_toolchains=false" >> .bazelrc.local
      - run:
          name: Build tests
          command: |
            bazel build --config ci //tests/...
      - run:
          name: Run tests
          command: |
            # Run the start script test.
            # Doesn't use the test suite binary, because that depends on nixpkgs dependencies.
            ./tests/run-start-script.sh
            # TODO: enable all tests for bindists
            # (this will require tests to both work with nixpkgs and hazel backends)

  build-darwin:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run:
          name: Install Nix
          command: |
            curl https://nixos.org/nix/install | sh

      - run:
          name: Install cachix
          shell: /bin/bash -eilo pipefail
          command: |
            nix-env -iA cachix -f https://github.com/NixOS/nixpkgs/tarball/db557aab7b690f5e0e3348459f2e4dc8fd0d9298

      - run:
          name: Run cachix
          shell: /bin/bash -eilo pipefail
          command: |
            cachix use tweag
            cachix push tweag --watch-store
          background: true

      - run:
          name: Configure
          command: |
            mkdir -p ~/.cache/bazel/

            echo "build:ci --host_platform=@rules_haskell//haskell/platforms:darwin_x86_64_nixpkgs" >> .bazelrc.local
            echo "build:ci --disk_cache=~/.cache/bazel/" >> .bazelrc.local
            echo "common:ci --test_tag_filters -dont_test_on_darwin" >> .bazelrc.local

      - restore_cache:
          keys: # see note about 'Disk cache'
              - v1-rules_haskell-empty-{{ .Branch }}-
              - v1-rules_haskell-cache-{{ .Branch }}-
              - v1-rules_haskell-cache-master-

      - run:
          name: Prefetch Stackage snapshot
          shell: /bin/bash -eilo pipefail
          command: |
            # Retry if needed due to network flakiness.
            nix-shell --arg docTools false --pure --run \
              'cmd="bazel fetch @stackage//..."; $cmd || $cmd || $cmd'
      - run:
          name: Build tests
          shell: /bin/bash -eilo pipefail
          command: |
            nix-shell --arg docTools false --pure --run \
              'bazel build --config ci //tests/...'
      - run:
          name: Run tests
          shell: /bin/bash -eilo pipefail
          command: |

            # Keep CI awake
            while true; do echo "."; sleep 60; done &

            nix-shell --arg docTools false --pure --run \
              'bazel build --config ci //tests:run-tests'
            # XXX 2019-01-22 Disable start script checking on Darwin
            # due to a clash between binutils and clang.
            nix-shell --arg docTools false --pure --run \
              './bazel-ci-bin/tests/run-tests --skip "/startup script/"'
            nix-shell --arg docTools false --pure --run \
              'bazel coverage //tests/... --config ci --build_tag_filters "coverage-compatible" --test_tag_filters "coverage-compatible" --test_output=all'


        # see note about 'Disk cache'
      - save_cache:
          key: v1-rules_haskell-cache-{{ .Branch }}-{{ .BuildNum }}
          paths:
              - ~/.cache/bazel/

      - run:
          name: Clean up cache
          shell: /bin/bash -eilo pipefail
          command: |
            rm -rf ~/.cache/bazel/
            mkdir -p ~/.cache/bazel/

      - save_cache:
          key: v1-rules_haskell-empty-master-{{ .BuildNum }}
          paths:
              - ~/.cache/bazel/

workflows:
  version: 2
  build:
    jobs:
      - build-linux-ghc-bindist
      - build-darwin:
          context: org-global # for the cachix token
