version: 2

jobs:

  # ATTN: when you change anything here, don’t forget to copy it to the build-darwin section
  build-linux:
    docker:
      - image: nixos/nix:2.1.3
    working_directory: ~/rules_haskell
    resource_class: large
    steps:
      - checkout
      - run:
          name: System dependencies
          command: |
            apk --no-progress update
            apk --no-progress add bash ca-certificates
            nix-channel --update
            # CircleCI and Nix sandboxing don't play nice. See
            # https://discourse.nixos.org/t/nixos-on-ovh-kimsufi-cloning-builder-process-operation-not-permitted/1494/5
            mkdir -p /etc/nix && echo "sandbox = false" > /etc/nix/nix.conf
      - run:
          name: Build
          command: |
            nix-shell --arg docTools false --pure --run 'bazel build --config ci --jobs=2 //tests/...'
      - run:
          name: Run tests
          # bazel does not support recursive bazel call, so we
          # cannot use bazel run here because the test runner uses
          # bazel
          command: |
            nix-shell --arg docTools false --pure --run 'bazel build //tests:run-tests && ./bazel-bin/tests/run-tests'

  build-darwin:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run:
          name: Install Nix
          command: |
            curl https://nixos.org/nix/install | sh
      - run:
          name: Build
          shell: /bin/bash -eilo pipefail
          command: |
            nix-shell --arg docTools false --pure --run 'bazel build --config ci --jobs=2 //tests/...'
      - run:
          name: Run tests
          shell: /bin/bash -eilo pipefail
          command: |
            nix-shell --arg docTools false --pure --run 'bazel build //tests:run-tests && ./bazel-bin/tests/run-tests'

workflows:
  version: 2
  build:
    jobs:
      - build-linux
      - build-darwin
