version: 2

jobs:
  build-linux:
    docker:
      - image: nixos/nix:1.11.14
    working_directory: ~/rules_haskell
    steps:
      - checkout
      - run:
          name: System dependencies
          command: |
            apk --no-progress update
            apk --no-progress add bash ca-certificates
            nix-channel --update
            nix-env -iA nixpkgs.bazel nixpkgs.binutils nixpkgs.python nixpkgs.go
      - run:
          name: Build
          command: bazel build --jobs=2 //... @haskell_zlib//...
      - run:
          name: Run tests
          command: bazel test //... --config=ci
      - run:
          name: Test targets that must fail
          command: tests/targets-that-must-fail/run-tests.sh
      - run:
          name: Test REPL for libraries
          command: |
            bazel build //tests/repl-targets:hs-lib-repl
            bazel-bin/tests/repl-targets/hs-lib-repl -e "foo 10"
      - run:
          name: Test REPL for binaries
          command: |
            bazel build //tests/repl-targets:hs-bin-repl
            bazel-bin/tests/repl-targets/hs-bin-repl -e ":main"
      - run:
          name: Test start script
          command: |
            pwd=$(pwd)
            cd $(mktemp -d)
            $pwd/start

            # Copy the bazel configuration, this is only useful for CI
            mkdir tools
            cp $pwd/tools/bazel.rc tools/bazel.rc

            bazel fetch //... --config=ci

  build-darwin:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run:
          name: Install Nix
          command: |
            # XXX Workaround a Nix 2.0 bug by sticking to Nix 1.11 for
            # now. See https://github.com/NixOS/nix/issues/1988.
            nixurl=https://nixos.org/releases/nix/nix-1.11.16/nix-1.11.16-x86_64-darwin.tar.bz2
            curl -s $nixurl | tar xf - -C /tmp
            # XXX Even when script runs correctly, it still returns non-zero rc.
            # So ignore it for now.
            yes | /tmp/nix-1.11.16-x86_64-darwin/install || true
      - run:
          name: System dependencies
          command: |
            brew update
            brew install bazel
            brew install go
      - run:
          name: Build
          shell: /bin/bash -eilo pipefail
          command: bazel build --jobs=2 //...
      - run:
          name: Run tests
          shell: /bin/bash -eilo pipefail
          command: bazel test //... --config=ci
      - run:
          name: Test targets that must fail
          shell: /bin/bash -eilo pipefail
          command: tests/targets-that-must-fail/run-tests.sh

workflows:
  version: 2
  build:
    jobs:
      - build-linux
      - build-darwin
